[package]
name = "fastdiff"
version = "0.1.2"
authors = ["Syrus <me@syrusakbary.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
difflib = "0.4.0"
wee_alloc = "0.4.4"
